install_slurmbuild:
  pkg.installed:
    - pkgs:
      - bzip2
      - freeipmi-devel
      - gcc
      - gtk2-devel
      - hwloc-devel
      - json-devel
      - lua-devel
      - make
      - mariadb-devel
      - mariadb-server
      - munge-devel
      - munge-libs
      - ncurses-devel
      - numactl-devel
      - openssl-devel
      - pam-devel
      - perl
      - perl-ExtUtils-MakeMaker
      - readline-devel
      - rpm-build
      - rpmdevtools
      - rrdtool-devel
